canteen/orders/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FieldList, SelectField
from wtforms.fields.html5 import DateTimeField, DateField
from wtforms.validators import DataRequired

class OrderFormForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    date_expired = DateField("Expiration datetime str", validators=[DataRequired()])
    date_started = DateField("Starting datetime str", validators=[DataRequired()])

    submit = SubmitField('Post')

# creating multiple fields for each day of the week 
fields = {'monday1': 'Monday option 1', 'monday2': 'Monday option 2', 'monday3': 'Monday option 3',
'tuesday1': 'Tuesday option 1', 'tuesday2': 'Tuesday option 2', 'tuesday3': 'Tuesday option 3',
'wednesday1': 'Wednesday option 1', 'wednesday2': 'Wednesday option 2', 'wednesday3': 'Wednesday option 3',
'thursday1': 'Thursday option 1', 'thursday2': 'Thursday option 2', 'thursday3': 'Thursday option 3',
'friday1': 'Friday option 1', 'friday2': 'Friday option 2', 'friday3': 'Friday option 3'}

for key, value in fields.items():
    setattr(OrderFormForm, key, StringField(value))

class OrderFormResponse(FlaskForm):
    monday = SelectField('Monday', coerce=str, validators=[DataRequired()], validate_choice=False)
    tuesday = SelectField('Tuesday', coerce=str, validators=[DataRequired()], validate_choice=False)
    wednesday = SelectField('Wednesday', coerce=str, validators=[DataRequired()], validate_choice=False)
    thursday = SelectField('Thursday', coerce=str, validators=[DataRequired()], validate_choice=False)
    friday = SelectField('Friday', coerce=str, validators=[DataRequired()], validate_choice=False)

    submit = SubmitField('Complete order')

canteen/orders/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask.helpers import make_response
from flask_login import current_user, login_required
from canteen import db, admin_permission
from canteen.models import OrderForm, OrderResponse, User
from canteen.orders.forms import OrderFormForm, OrderFormResponse
from datetime import date, datetime, timedelta
from canteen.orders.utils import Group, append_options, generate_orderForm_name, get_multiple_order_choices_counts, get_user_response, add_order_choices, next_monday, generate_orderForm_name
import pdfkit

orders = Blueprint('orders', __name__)

@orders.route('/orders/forms/new', methods=['GET', 'POST'])
@login_required
@admin_permission.require()
def new_order():
    form = OrderFormForm()
    if form.validate_on_submit():
        order = OrderForm(title=form.title.data, date_expired=form.date_expired.data, date_started=form.date_started.data, monday1=form.monday1.data, monday2=form.monday2.data, monday3=form.monday3.data, tuesday1=form.tuesday1.data, tuesday2=form.tuesday2.data, tuesday3=form.tuesday3.data, wednesday1=form.wednesday1.data, wednesday2=form.wednesday2.data, wednesday3=form.wednesday3.data, thursday1=form.thursday1.data, thursday2=form.thursday2.data, thursday3=form.thursday3.data, friday1=form.friday1.data, friday2=form.friday2.data, friday3=form.friday3.data)
        db.session.add(order)
        db.session.commit()
        flash('Your order form has been created!', 'success')
        return redirect(url_for('main.home'))
    else: 
        form.title.data = generate_orderForm_name()
        form.date_started.data = next_monday()
        form.date_expired.data = next_monday()
    return render_template("create_form.html", title="New Order Form", form=form, legend='New Order Form')

@orders.route('/orders/<int:order_form_id>/fill', methods=['GET', 'POST'])
@login_required
def fill_order(order_form_id):
    order_form = OrderForm.query.get_or_404(order_form_id)
    form = OrderFormResponse()
    if current_user.id in order_form.users_responded():
        flash('You have already placed an order for this week. Please try to update it', 'danger')
        return redirect(url_for("main.home"))
    if form.validate_on_submit():
        response = OrderResponse(monday=str(form.monday.data), tuesday=form.tuesday.data, wednesday=form.wednesday.data, thursday=form.thursday.data, friday=form.friday.data, user_id=current_user.id, form_id = order_form_id)
        db.session.add(response)
        db.session.commit()
        flash('Your order has been succesfully sent!', 'success')
        return redirect(url_for('main.home'))
    else:
        form = add_order_choices(form, order_form)
        form.monday.data = 'None'
        form.tuesday.data = 'None'
        form.wednesday.data = 'None'
        form.thursday.data = 'None'
        form.friday.data = 'None'
    return render_template('order_form.html', form=form, title="Create Order", legend='Fill', name=order_form.title)

@orders.route('/orders/view')
@login_required
def order_view():
    page = request.args.get('page', 1, type=int)
    orders = OrderForm.query.order_by(OrderForm.date_posted.desc()).paginate(per_page=3, page=page)
    return render_template("your_orders.html", orders=orders, get_user_response=get_user_response, datetime=datetime, timedelta=timedelta)

@orders.route('/orders/<int:order_id>/view')
@login_required
def single_order_view(order_id):
    order = OrderForm.query.get_or_404(order_id)
    return render_template("order.html", order=order, get_user_response=get_user_response, datetime=datetime, timedelta=timedelta)

@orders.route('/orders/<int:order_id>/update', methods=['GET', 'POST'])
@login_required
def update_order(order_id):
    order = OrderForm.query.get_or_404(order_id)
    response = get_user_response(order)
    if not response:
        return redirect(url_for("orders.fill_order"), order_id)
    form = OrderFormResponse()
    if form.validate_on_submit():
        response.monday = form.monday.data
        response.tuesday = form.tuesday.data
        response.wednesday = form.wednesday.data
        response.thursday = form.thursday.data
        response.friday = form.friday.data
        db.session.commit()
        flash('Your order has been updated!', 'success')
        return redirect(url_for('orders.single_order_view', order_id=order_id))
    elif request.method == 'GET':
        form = add_order_choices(form, order)
        form.monday.data = response.monday
        form.tuesday.data = response.tuesday
        form.wednesday.data = response.wednesday
        form.thursday.data = response.thursday
        form.friday.data = response.friday
    return render_template("order_form.html", title="Update Order", form=form, legend='Update', name=order.title)
    
@orders.route('/orders/forms/<int:form_id>/view')
@login_required
@admin_permission.require()
def single_form_view(form_id):
    order = OrderForm.query.get_or_404(form_id)
    choices = order.get_order_choices_counts()
    groups = Group.get_groups()
    return render_template("form.html", order=order, choices=choices, groups=groups, len=len, zip=zip)

@orders.route('/orders/forms/<int:form_id>/pdf')
@login_required
@admin_permission.require()
def single_form_pdf(form_id):
    options = {'enable-local-file-access': None}
    order = OrderForm.query.get_or_404(form_id)
    choices = order.get_order_choices_counts()
    groups = Group.get_groups()
    rendered = render_template("pdf.html", order=order, choices=choices, groups=groups, len=len, zip=zip)
    pdf = pdfkit.from_string(rendered, False, options=options)
   
    response = make_response(pdf)
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = 'attachment; filename=output.pdf'
    
    return response

@orders.route('/orders/forms/view')
@login_required
@admin_permission.require()
def order_forms():
    page = request.args.get('page', 1, type=int)
    orders = OrderForm.query.order_by(OrderForm.date_posted.desc()).paginate(per_page=3, page=page)
    choices = get_multiple_order_choices_counts(orders)
    return render_template("order_forms.html", orders=orders, choices=choices, len=len, zip=zip)

canteen/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from canteen import db, bcrypt, admin_permission
from canteen.models import User
from canteen.users.forms import (RegistrationForm, LogInForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from canteen.users.utils import save_picture, send_reset_email
from flask_principal import Identity, AnonymousIdentity, identity_changed, identity_loaded, RoleNeed

users = Blueprint('users', __name__)

@identity_loaded.connect
def on_identity_loaded(sender, identity):
    # Set the identity user object for permissions
    identity.user = current_user
    if hasattr(current_user, "role"):
        identity.provides.add(RoleNeed(current_user.role))

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        #hash the password
        hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        #create the new user object and add it to the database
        user = User(username=form.username.data, email=form.email.data, password=hashed_pass, group=form.group.data, 
                    school_id = form.school_id.data, last_name=form.last_name.data, first_name=form.first_name.data)
        db.session.add(user)
        db.session.commit()

        flash(f'Account created for {form.username.data} successfully!', 'success')

        return redirect(url_for('users.login'))
    return render_template("register.html", title="Register", form=form)

#login page route
@users.route('/login', methods=['GET', 'POST'])
def login():
    #redirecting to home page if user is already logged in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LogInForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        #if user exists and if the password matches with the password in the database
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            #principal identity gets updated with the user object
            identity = Identity(user.id)
            if current_user.role == "admin":
                identity.can(admin_permission)
            identity_changed.send(current_app._get_current_object(), identity=identity)
            next_page = request.args.get('next')
            #redirecting to the page that the user was trying to access before logging in or to the home page
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("Wrong email or password. Please try again", 'danger')        
    return render_template("login.html", title="LogIn", form=form)

@users.route('/logout')
def logout():
    logout_user()
    identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())
    return redirect(url_for('main.home'))
    

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account data has been updated!", 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("account.html", title="Account", image_file=image_file, form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        #sending the user an email with a link to reset their password (token)
        send_reset_email(user)
        flash("email has been sent with instructions to reset your password.", 'info')
        return redirect(url_for('users.login'))
    return render_template("reset_request.html", title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    #verifying the token and getting the user object
    user = User.verify_reset_token(token)
    # if the token is invalid or has expired, redirect to the reset request page
    if user is None:
        flash('This is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))  
    form = ResetPasswordForm()
    if form.validate_on_submit():
        #hash the password
        hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        #update the password in the database
        user.password = hashed_pass
        db.session.commit()
        flash('Your password has been updated', 'success')
        return redirect(url_for('users.login'))
    return render_template("reset_token.html", title='Reset Password', form=form)

canteen/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>New form</h1>
{% endblock content %}

canteen/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{image_file}}">
            <div class="media-body">
            <h2 class="account-heading">{{current_user.username}}</h2>
            <p class="text-secondary">{{current_user.email}}</p>
            </div>
        </div>

        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form">
                <legend class= "border-bottom mb-4">Account information</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                        
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                        
                </div>

            <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger"> {{ error }}</span> </br>
                        {% endfor %}
                    {% endif %}                        
                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>     
        </form>

        <div class="border-top pt-3">
            <small class "text-muted">
            Already have an account? <a class "ml-2" href="{{ url_for('users.login') }}"> Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}

canteen/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    {% if title %}
        <title>Canteen - {{ title }}</title>
    {% else %}
        <title>Canteen</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Canteen</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            {% if current_user.role == 'admin' %}
              <a class="nav-item nav-link" href={{url_for('orders.order_forms')}}>Order Forms</a>
              <a class="nav-item nav-link" href={{url_for('orders.new_order')}}>New Form</a>
            {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            {% if current_user.is_authenticated %}
              {% if current_user.role != 'admin' %}
                <a class="nav-item nav-link" href={{url_for('orders.order_view')}}>My Orders</a>
              {%else%}
              <a class="nav-item nav-link" href="\admin">Admin Panel</a>
              {% endif %}
              <a class="nav-item nav-link" href={{url_for('users.logout')}}>Log Out</a>
              <a class="nav-item nav-link" href={{url_for('users.account')}}>Account</a>
              <a href={{url_for('users.account')}}>
                <img class="rounded-circle nav-img" src="{{url_for('static', filename='profile_pics/' + current_user.image_file)}}">
              </a>
              
            {% else %}
              <a class="nav-item nav-link" href={{url_for('users.login')}}>Log In</a>
              <a class="nav-item nav-link" href={{url_for('users.register')}}>Register</a>
            {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div>
        <div>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

canteen/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class= "border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}                       
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}                        
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request')}}">Forgot Password?</a>
                </small> 
            </div>    

        </form>
    </div>
    <div class="border-top pt-3">
        <small class "text-muted">
        Do not have an account? <a class="ml-2" href="{{ url_for('users.register') }}"> Sign Up</a>
        </small>
    </div>
{% endblock content %}

canteen/templates/order_forms.html
{% extends "layout.html" %}
{% block content %}

 {% for order, single_order_choices in zip(orders.items, choices) %}
  <article class="media content-section">
			<div class="media-body">
				<div class="article-metadata">
					<a href="{{url_for("orders.single_form_view", form_id=order.id)}}"><h1>{{order.title}}</h1></a>
					<small class="text-muted">{{ order.date_posted.strftime('%Y-%m-%d') }}</small>
				</div>
				<div class-"content-section">
					<div class="row mb-2 mt-3">
						<div class="col">
							<h3>Date Expires:</h3> 
							<p>{{order.date_expired}}</p>
						</div>
						<div class="col">
							<h3>Date Starts:</h3>
							<p>{{order.date_started}}</p>
						</div>
						<div class="col">
							<div>
							<h3>Number of orders:<span class="text-danger ml-3">{{len(order.responses)}}</span></h3>
							</div>
						</div>
					</div>
					<h3 class="mb-2">Choices</h3>
					<div class="row mb-2 ml-1 mr-1"> 
						{% for day, options in single_order_choices.items() %}
						<div class="col content-section">
							<h5>{{day.capitalize()}}</h5>
							{% for choice, count in options.items() %}
								<div class="row">
									<div class="col-8">{{choice.capitalize()}}</div>
									<div class="col-4">{{count}}</div>
								</div>  
							{% endfor %}
							</div>
						{% endfor %} 
					</div>
				</div>
			</div>
		</article>
    {% endfor %}

    {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
      {% if page_num %}
        {% if orders.page == page_num %}
          <a class="btn btn-page mb-4" href="{{url_for('orders.order_forms',page=page_num)}}">{{page_num}}</a>      
        {% else %}
          <a class="btn btn-page-outline mb-4" href="{{url_for('orders.order_forms',page=page_num)}}">{{page_num}}</a>
        {% endif %}

      {% else %}  
        ...
      {% endif %}

    {% endfor %}
{% endblock content %}

canteen/templates/your_orders.html
{% extends "layout.html" %}
{% block content %}
    {% for order in orders.items %}
        {% set time_left = order.date_expired - datetime.now()%}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a href="{{url_for("orders.single_order_view", order_id=order.id)}}"><h1>{{order.title}}</h1></a>
                    <small class="text-muted">{{ order.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <div class-"content-section container">
                {% set response = get_user_response(order)%}
                {% if response %}
                    <div class="row">
                        {% if time_left > timedelta(0) %}
                            <div class="col pt-md-2"><a class="btn btn-outline-secondary btn-lg" href="{{url_for("orders.update_order", order_id=order.id)}}">Update</a></div>
                            <div class="col-sm">
                                <h4>Time left to update:</h4>
                                <p>{{time_left}}</p> 
                            </div>      
                        {% else %}
                            <div class="col-sm">
                                <h4>You can no longer update your order</h4>
                            </div>  
                        {% endif %}
                    </div>

                    <div class="pt-md-5">
                        <h2>Your Order:</h2>
                        <div class="content-section">
                            <div class="row">
                                <div class="col-sm"><h4>Monday:</h4></div>
                                {% if response.monday == "None" %}
                                    <div class="col-sm"><h4 class="text-danger">{{response.monday}}</h4></div>
                                {% else %}
                                    <div class="col-sm"><h4>{{response.monday}}</h4></div>
                                {% endif %}
                                
                            </div>
                            <div class="row">
                                <div class="col-sm"><h4>Tuesday:</h4></div>
                                {% if response.tuesday == "None" %}
                                    <div class="col-sm"><h4 class="text-danger">{{response.tuesday}}</h4></div>
                                {% else %}
                                    <div class="col-sm"><h4>{{response.tuesday}}</h4></div>
                                {% endif %}
                            </div>
                            <div class="row">
                                <div class="col-sm"><h4>Wednesday:</h4></div>
                                {% if response.wednesday == "None" %}
                                    <div class="col-sm"><h4 class="text-danger">{{response.wednesday}}</h4></div>
                                {% else %}
                                    <div class="col-sm"><h4>{{response.wednesday}}</h4></div>
                                {% endif %}
                            </div>
                            <div class="row">
                                <div class="col-sm"><h4>Thursday:</h4></div>
                                {% if response.thursday == "None" %}
                                    <div class="col-sm"><h4 class="text-danger">{{response.thursday}}</h4></div>
                                {% else %}
                                    <div class="col-sm"><h4>{{response.thursday}}</h4></div>
                                {% endif %}
                            </div>
                            <div class="row">
                                <div class="col-sm"><h4>Friday:</h4></div>
                                {% if response.friday == "None" %}
                                    <div class="col-sm"><h4 class="text-danger">{{response.friday}}</h4></div>
                                {% else %}
                                    <div class="col-sm"><h4>{{response.friday}}</h4></div>
                                {% endif %}
                            </div>
                        </div>  
                    </div>
                {% else %}
                    <div class="row">
                        {% if time_left > timedelta(0) %}
                            <div class="col pt-md-2"><a class="btn btn-outline-secondary btn-lg" href="{{url_for("orders.fill_order", order_form_id=order.id)}}">Create Order</a></div>
                            <div class="col-sm">
                                <h4>Time left to create order:</h4>
                                <p>{{time_left}}</p> 
                            </div>      
                        {% else %}
                            <div class="col-sm">
                                <h4>You can no longer create this order</h4>
                            </div>  
                        {% endif %}
                    </div>
                {% endif %}

        </article>

    {% endfor %}

    {% for page_num in orders.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
      {% if page_num %}
        {% if orders.page == page_num %}
          <a class="btn btn-info mb-4" href="{{url_for('orders.order_view',page=page_num)}}">{{page_num}}</a>      
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{url_for('orders.order_view',page=page_num)}}">{{page_num}}</a>
        {% endif %}

      {% else %}  
        ...
      {% endif %}


    {% endfor %}
{% endblock content %}